Webuygulamageliştirmevize/Models/ErrorViewModel.cs
using System;

namespace Webuygulamageliştirmevize.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Webuygulamageliştirmevize/Models/müşteri.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Webuygulamageliştirmevize.Models
{
    public class müşteri
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
       
    }
}

Webuygulamageliştirmevize/Models/müşteriveri.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Webuygulamageliştirmevize.Models
{
    public class müşteriveri
    {
        public static List<müşteri> müşteriler = new List<müşteri>()
        {
            new müşteri()
                        {
                            Id = 1,
                            Ad = "Ahmet Yiğit",
                            Soyad = "UYSAL",
                           
                        },
            new müşteri()
                        {
                            Id = 2,
                            Ad = "Emre",
                            Soyad = "ŞAHİN",
                            
                        },
            new müşteri()
                        {
                            Id = 3,
                            Ad = "Emine",
                            Soyad = "TOK",
                           
                        },

             new müşteri()
                        {
                            Id = 4,
                            Ad = "Mustafa",
                            Soyad = "KIR",

                        },

              new müşteri()
                        {
                            Id = 5,
                            Ad = "Furkan",
                            Soyad = "AL",

                        },


               new müşteri()
                        {
                            Id = 6,
                            Ad = "Selim",
                            Soyad = "YİĞİT",

                        },

                new müşteri()
                        {
                            Id = 7,
                            Ad = "Emirhan",
                            Soyad = "BUĞAN",

                        },








        };
    }
}

Webuygulamageliştirmevize/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Webuygulamageliştirmevize.Models;

namespace Webuygulamageliştirmevize.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult müşteri()
        {
            return View();
        }

        public IActionResult müşterikayıt()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Webuygulamageliştirmevize/Controllers/müşteriController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Webuygulamageliştirmevize.Controllers
{
    public class müşteriController : Controller
    {

        public IActionResult Listele()
        {
            return View(Models.müşteriveri.müşteriler);
        }

        public IActionResult Yeni()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Yeni(Models.müşteri yeniOgrenci)
        {
            Models.müşteriveri.müşteriler.Add(yeniOgrenci);
            return RedirectToAction("Listele");
        }

        public IActionResult Guncelle(int müşteriId)
        {

            var r = Models.müşteriveri.müşteriler.FirstOrDefault(x => x.Id == müşteriId);
            return View(r);


        }

        [HttpPost]
        public IActionResult Guncelle(Models.müşteri müşteri)
        {
            var c = Models.müşteriveri.müşteriler.FirstOrDefault(x => x.Id == müşteri.Id);

            var r = Models.müşteriveri.müşteriler.FirstOrDefault(x => x.Id == müşteri.Id);
            r.Ad = müşteri.Ad;
            r.Soyad = müşteri.Soyad;
           

            Models.müşteriveri.müşteriler.Remove(c);

            Models.müşteriveri.müşteriler.Add(r);

            return RedirectToAction("listele");
        }


        public IActionResult Detay(int id)
        {
            var r = Models.müşteriveri.müşteriler.FirstOrDefault(x => x.Id == id);
            return View(r);
        }


        public IActionResult Sil(int id)
        {
            var r = Models.müşteriveri.müşteriler.FirstOrDefault(x => x.Id == id);
            return View(r);
        }

        [HttpPost]
        public IActionResult Sil(Models.müşteri müşteri)
        {
            var r = Models.müşteriveri.müşteriler.FirstOrDefault(x => x.Id == müşteri.Id);
            Models.müşteriveri.müşteriler.Remove(r);
            return RedirectToAction("Listele");
        }












    }
}

Webuygulamageliştirmevize/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Başlangıç Sayfası";
}

<div class="text-center">
    <h1 class="display-4">İPEKYOLU A.Ş.</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p> 
</div>

Webuygulamageliştirmevize/Views/Home/müşteri.cshtml
@{
    ViewData["Title"] = "Müşteri";
}

<h1>Müşteri bilgileri hakkında</h1>

<h4>Tüm çalışanlarımızın dikkatine !!!!</h4>
<p> Merhaba arkadaşlar, yeni alınan kararla satış yaptığınınız tüm müşterilerimizin bilgilerini girmek herkesin kendi sorumluluğuna aittir.Tüm müşerilerimizin bilgilerinin eksiksiz ve doğru bir şekilde girildiğinden emin olunuz aksi taktirde yaptığınız satışlardan pirim alamayacaksınız.</p><br />
<p>Sistemimize aşağıdaki linkten ulaşabilirsiniz:</p><br />
 <a href="@Url.Action("yeni","müşteri")">kayıt Sayfayasına Git</a>

Webuygulamageliştirmevize/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Webuygulamageliştirmevize</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Webuygulamageliştirmevize</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Başlangıç</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Hakkında</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="müşteri">Müşteri</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="müşteri" asp-action="yeni">müşterikayıt</a>
                        </li>




                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Webuygulamageliştirmevize - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Webuygulamageliştirmevize/Views/müşteri/Detay.cshtml
@model Webuygulamageliştirmevize.Models.müşteri

@{
    ViewData["Title"] = "Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detay</h1>

<div>
    <h4>müşteri</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Soyad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Soyad)
        </dd>
    </dl>
</div>
<div>
    
    <div><a href="@Url.Action("listele","müşteri")">listeye  Git</a></div>
</div>

Webuygulamageliştirmevize/Views/müşteri/Guncelle.cshtml
@model Webuygulamageliştirmevize.Models.müşteri

@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Guncelle</h1>

<h4>müşteri</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Guncelle">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soyad" class="control-label"></label>
                <input asp-for="Soyad" class="form-control" />
                <span asp-validation-for="Soyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <div><a href="@Url.Action("listele","müşteri")">listeye  Git</a></div>
</div>

Webuygulamageliştirmevize/Views/müşteri/Listele.cshtml
@model IEnumerable<Webuygulamageliştirmevize.Models.müşteri>

@{
    ViewData["Title"] = "Listele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listele</h1>

<p>
    <a asp-action="yeni">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Soyad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Soyad)
            </td>
            <td>
                @Html.ActionLink("guncelle", "guncelle", new {  id=item.Id }) |
                @Html.ActionLink("detay", "detay", new { id = item.Id }) |
                @Html.ActionLink("sil", "sil", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Webuygulamageliştirmevize/Views/müşteri/Sil.cshtml
@model Webuygulamageliştirmevize.Models.müşteri

@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sil</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>müşteri</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Soyad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Soyad)
        </dd>
    </dl>
    
    <form asp-action="Sil">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="listele">Back to List</a>
    </form>
</div>

Webuygulamageliştirmevize/Views/müşteri/Yeni.cshtml
@model Webuygulamageliştirmevize.Models.müşteri

@{
    ViewData["Title"] = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Yeni</h1>

<h4>müşteri</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Yeni">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soyad" class="control-label"></label>
                <input asp-for="Soyad" class="form-control" />
                <span asp-validation-for="Soyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div><a href="@Url.Action("listele","müşteri")">listeye  Git</a></div>